services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - pg-files:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=oauth2-bff-demo

volumes:
  pg-files: